#!/bin/bash

# 100 Viral and Interesting Solana Scenarios for OpenSVM API
# Using port 3000 only

BASE_URL="https://osvm.ai/api/getAnswer"
DELAY=2

echo "🚀 Starting 100 Viral Solana Scenarios Test"
echo "========================================"

# Function to make API call
query_api() {
    local count=$1
    local question=$2
    echo -e "\n🔍 Query $count: $question"
    echo "----------------------------------------"
    curl -s -X POST -H "Content-Type: application/json" -d "{\"question\":\"$question\",\"sources\":[]}" $BASE_URL
    echo -e "\n"
    sleep $DELAY
}

# 1-10: Network and Performance
query_api 1 "What is the current Solana TPS?"
query_api 2 "How many validators are currently active?"
query_api 3 "What is the current slot height?"
query_api 4 "Show me network performance over the last hour"
query_api 5 "What is the current epoch information?"
query_api 6 "How much SOL is currently staked?"
query_api 7 "What is the network's inflation rate?"
query_api 8 "Show me the top 5 validators by stake"
query_api 9 "What is the average block time?"
query_api 10 "How many transactions happened in the last slot?"
# 11-20: DeFi and Trading
query_api 11 "What are the top DeFi protocols on Solana?"
query_api 12 "Show me the best yield farming opportunities"
query_api 13 "What is the TVL of Raydium?"
query_api 14 "How do I swap tokens on Jupiter?"
query_api 15 "What are the hottest trading pairs today?"
query_api 16 "Show me arbitrage opportunities between DEXs"
query_api 17 "What is the current price of USDC on Solana?"
query_api 18 "How do I provide liquidity on Orca?"
query_api 19 "What are the fees for trading on Serum?"
query_api 20 "Show me the top performing DeFi tokens"

# 21-30: NFTs and Gaming
query_api 21 "What are the trending NFT collections today?"
query_api 22 "Show me the floor prices of top NFT collections"
query_api 23 "What are the most popular GameFi projects?"
query_api 24 "How do I mint an NFT on Solana?"
query_api 25 "What gaming tokens are pumping?"
query_api 26 "Show me NFT marketplace volume"
query_api 27 "What are the best play-to-earn games?"
query_api 28 "How do I create an NFT collection?"
query_api 29 "What is the rarity ranking of Solana Monkey Business?"
query_api 30 "Show me upcoming NFT drops"

# 31-40: Meme Coins and Social Tokens
query_api 31 "What are the hottest meme coins right now?"
query_api 32 "Show me coins that pumped 100x today"
query_api 33 "What is BONK doing today?"
query_api 34 "Find me the next potential gem"
query_api 35 "What meme coins have the highest volume?"
query_api 36 "Show me social tokens with communities"
query_api 37 "What is the market cap of SAMO?"
query_api 38 "Find coins with funny names"
query_api 39 "What community tokens are trending?"
query_api 40 "Show me tokens launched in the last 24 hours"

# 41-50: Development and Technical
query_api 41 "How do I build my first Solana program?"
query_api 42 "What is Anchor framework?"
query_api 43 "How do I deploy a smart contract?"
query_api 44 "What are the best Solana development tools?"
query_api 45 "How do I integrate Solana in my app?"
query_api 46 "What is a Program Derived Address?"
query_api 47 "How do I handle Solana transactions?"
query_api 48 "What are the latest Solana updates?"
query_api 49 "How do I optimize my program for speed?"
query_api 50 "What is the Solana consensus mechanism?"

# 51-60: Wallets and Security
query_api 51 "How do I secure my Solana wallet?"
query_api 52 "What are the best Solana wallets?"
query_api 53 "How do I recover a lost wallet?"
query_api 54 "What are hardware wallet options?"
query_api 55 "How do I protect against scams?"
query_api 56 "What are multi-sig wallets?"
query_api 57 "How do I backup my seed phrase?"
query_api 58 "What are the signs of a rug pull?"
query_api 59 "How do I verify transaction safety?"
query_api 60 "What are the best security practices?"

# 61-70: Cross-chain and Bridges
query_api 61 "How do I bridge ETH to Solana?"
query_api 62 "What are the best cross-chain bridges?"
query_api 63 "How do I move USDC from Ethereum?"
query_api 64 "What is Wormhole bridge?"
query_api 65 "How do I bridge Bitcoin to Solana?"
query_api 66 "What are wrapped tokens?"
query_api 67 "How do I use Portal bridge?"
query_api 68 "What are the bridge fees?"
query_api 69 "How do I bridge back to Ethereum?"
query_api 70 "What are cross-chain risks?"

# 71-80: Staking and Rewards
query_api 71 "How do I stake SOL for rewards?"
query_api 72 "What are the best validators to stake with?"
query_api 73 "What is liquid staking?"
query_api 74 "How do I unstake my SOL?"
query_api 75 "What are staking rewards rates?"
query_api 76 "How does validator commission work?"
query_api 77 "What is Marinade Finance?"
query_api 78 "How do I choose a validator?"
query_api 79 "What are the risks of staking?"
query_api 80 "How do I maximize staking rewards?"

# 81-90: Market Analysis and Prices
query_api 81 "What factors affect SOL price?"
query_api 82 "Is this a good time to buy SOL?"
query_api 83 "What are SOL price predictions?"
query_api 84 "How does Solana compare to Ethereum?"
query_api 85 "What drives Solana adoption?"
query_api 86 "What are market sentiment indicators?"
query_api 87 "How do I read Solana charts?"
query_api 88 "What are key resistance levels?"
query_api 89 "What news affects SOL price?"
query_api 90 "How do I time the market?"

# 91-100: Fun and Viral Scenarios
query_api 91 "If I bought $100 of SOL in 2020, what would it be worth?"
query_api 92 "What would happen if Solana processed 1 million TPS?"
query_api 93 "Can Solana flip Ethereum?"
query_api 94 "What if everyone staked their SOL?"
query_api 95 "How fast can Solana really go?"
query_api 96 "What is the craziest Solana fact?"
query_api 97 "Who are the biggest Solana whales?"
query_api 98 "What would Solana look like in 2030?"
query_api 99 "Can you build the next Twitter on Solana?"
query_api 100 "What makes Solana the future of crypto?"

echo "🎉 Completed all 100 scenarios!"
echo "==============================="

# Scenarios 21-40: Advanced Trading and Analytics
test_scenario "How do I use Jupiter aggregator for best swap prices?" "DEX aggregation strategies"
test_scenario "What are the most liquid trading pairs on Solana?" "Liquidity analysis"
test_scenario "How do I analyze on-chain whale movements?" "Whale tracking methods"
test_scenario "What are the best tools for Solana portfolio tracking?" "Portfolio management"
test_scenario "How do I set up price alerts for Solana tokens?" "Price monitoring"
test_scenario "What are the top Solana tokens by market cap?" "Market cap rankings"
test_scenario "How do I identify new token launches early?" "Early token detection"
test_scenario "What are the most profitable Solana trading bots?" "Trading bot strategies"
test_scenario "How do I analyze Solana options and derivatives?" "Derivatives trading"
test_scenario "What are the best Solana lending protocols?" "Lending opportunities"
test_scenario "How do I track Solana ecosystem funding rounds?" "Investment tracking"
test_scenario "What are the highest APY farms on Solana right now?" "High-yield farming"
test_scenario "How do I use flash loans on Solana?" "Flash loan mechanics"
test_scenario "What are the best Solana perpetual trading platforms?" "Perp trading platforms"
test_scenario "How do I hedge my Solana positions?" "Risk management"
test_scenario "What are the top Solana index funds?" "Index investing"
test_scenario "How do I analyze Solana network congestion?" "Network performance"
test_scenario "What are the best Solana mobile wallets?" "Mobile wallet comparison"
test_scenario "How do I participate in Solana token sales?" "Token sale participation"
test_scenario "What are the most innovative Solana projects?" "Innovation spotting"

# Scenarios 41-60: NFTs and Digital Assets
test_scenario "How do I create and mint NFTs on Solana?" "NFT creation guide"
test_scenario "What are the best Solana NFT marketplaces?" "NFT marketplace comparison"
test_scenario "How do I value Solana NFTs?" "NFT valuation methods"
test_scenario "What are the rarest Solana NFT collections?" "Rare NFT discovery"
test_scenario "How do I track NFT floor prices on Solana?" "NFT price tracking"
test_scenario "What are the best Solana NFT analytics tools?" "NFT analytics platforms"
test_scenario "How do I create NFT royalties on Solana?" "NFT royalty systems"
test_scenario "What are the top Solana art collections?" "Art NFT collections"
test_scenario "How do I create dynamic NFTs on Solana?" "Dynamic NFT development"
test_scenario "What are the best Solana NFT drops this month?" "Upcoming NFT drops"
test_scenario "How do I create NFT collections with utility?" "Utility NFT design"
test_scenario "What are the most expensive Solana NFTs ever sold?" "High-value NFT sales"
test_scenario "How do I create music NFTs on Solana?" "Music NFT creation"
test_scenario "What are the best Solana avatar projects?" "Avatar NFT projects"
test_scenario "How do I fractionalize NFTs on Solana?" "NFT fractionalization"
test_scenario "What are the top Solana metaverse projects?" "Metaverse platforms"
test_scenario "How do I create NFT staking rewards?" "NFT staking mechanisms"
test_scenario "What are the best Solana NFT lending platforms?" "NFT lending options"
test_scenario "How do I create cross-chain NFTs?" "Cross-chain NFT bridging"
test_scenario "What are the top Solana gaming NFTs?" "Gaming NFT ecosystems"

# Scenarios 61-80: DeFi and Advanced Protocols
test_scenario "How do I create a Solana AMM pool?" "AMM pool creation"
test_scenario "What are the best Solana derivatives protocols?" "Derivatives platforms"
test_scenario "How do I create synthetic assets on Solana?" "Synthetic asset creation"
test_scenario "What are the top Solana insurance protocols?" "DeFi insurance options"
test_scenario "How do I create prediction markets on Solana?" "Prediction market development"
test_scenario "What are the best Solana DAO tools?" "DAO creation platforms"
test_scenario "How do I create tokenized real estate on Solana?" "Real estate tokenization"
test_scenario "What are the top Solana privacy protocols?" "Privacy-focused projects"
test_scenario "How do I create decentralized identity on Solana?" "DID implementation"
test_scenario "What are the best Solana oracle solutions?" "Oracle service comparison"
test_scenario "How do I create cross-chain bridges on Solana?" "Bridge development"
test_scenario "What are the top Solana algorithmic stablecoins?" "Algorithmic stablecoin analysis"
test_scenario "How do I create automated trading strategies?" "Automated trading setup"
test_scenario "What are the best Solana governance tokens?" "Governance token analysis"
test_scenario "How do I create liquidity mining programs?" "Liquidity incentive design"
test_scenario "What are the top Solana launchpads?" "Token launch platforms"
test_scenario "How do I create bonds and fixed-income on Solana?" "Fixed-income protocols"
test_scenario "What are the best Solana asset management tools?" "Asset management platforms"
test_scenario "How do I create options protocols on Solana?" "Options platform development"
test_scenario "What are the top Solana structured products?" "Structured product analysis"

# Scenarios 81-100: Emerging Trends and Advanced Use Cases
test_scenario "How do I create AI-powered trading bots on Solana?" "AI trading integration"
test_scenario "What are the top Solana RWA (Real World Assets) projects?" "RWA tokenization"
test_scenario "How do I create carbon credit markets on Solana?" "Carbon trading platforms"
test_scenario "What are the best Solana social trading platforms?" "Social trading networks"
test_scenario "How do I create subscription services on Solana?" "Subscription model development"
test_scenario "What are the top Solana infrastructure providers?" "Infrastructure service comparison"
test_scenario "How do I create decentralized VPNs on Solana?" "dVPN development"
test_scenario "What are the best Solana data analytics platforms?" "Data analytics tools"
test_scenario "How do I create IoT payments on Solana?" "IoT payment systems"
test_scenario "What are the top Solana energy trading platforms?" "Energy market tokenization"
test_scenario "How do I create decentralized storage on Solana?" "Storage protocol development"
test_scenario "What are the best Solana streaming protocols?" "Streaming service platforms"
test_scenario "How do I create supply chain tracking on Solana?" "Supply chain transparency"
test_scenario "What are the top Solana creator economy platforms?" "Creator monetization tools"
test_scenario "How do I create decentralized computing on Solana?" "Distributed computing networks"
test_scenario "What are the best Solana cross-chain protocols?" "Interoperability solutions"
test_scenario "How do I create regulatory-compliant DeFi?" "Compliance framework development"
test_scenario "What are the top Solana institutional services?" "Institutional platform comparison"
test_scenario "How do I create quantum-resistant security on Solana?" "Quantum security implementation"
test_scenario "What are the future trends in the Solana ecosystem?" "Ecosystem future analysis"

echo "Completed all 100 scenarios!"
echo "Total scenarios tested: $((SCENARIO_COUNT - 1))"
